stages:
  - lint
  - audit
  - test
  - build
  - scan
  - push
  - release

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'

default:
  image: ${ARTIFACTORY_SERVER}/sds/sdd-common-ci:2026.9.1

workflow:
  auto_cancel:
    on_new_commit: interruptible

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOCACHE: $CI_PROJECT_DIR/.go-build

go-lint:
  stage: lint
  extends: .go-cache
  variables:
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  tags:
    - sds-test
  before_script:
    - mkdir -p .cache
  script:
    - golangci-lint run -v ./... --timeout 10m --output.code-climate.path stdout | tee gl-code-quality-report.json
    - go fmt ./...
    - go vet ./...
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  after_script:
    - sudo rm -rf .go/pkg

jfrog-go-audit:
  stage: audit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME != "renovate-bot"'
      when: always
      variables:
        WATCH: sds-watch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME == "renovate-bot"'
      variables:
        WATCH: sds-renovate
  tags:
    - sds-test
  before_script:
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    # Audit Go project
    - jf audit --go --licenses --extended-table --watches=$WATCH

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      interruptible: true
  tags:
    - sds-test
  resource_group: testing
  before_script:
    - docker stop $(docker ps -q --filter "name=test-C4ghTransit") 2>/dev/null || true
  script:
    - export ARTIFACTORY_USER=$ARTIFACTORY_READ_ONLY_USER
    - export ARTIFACTORY_USER_PASSWORD=$ARTIFACTORY_READ_ONLY_PASSWORD
    - export ARTIFACTORY_SERVER=$ARTIFACTORY_SERVER
    - go test -timeout 40m -v ./c4ghtransit

build-binary:
  stage: build
  tags:
    - sds-build
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      interruptible: true
  before_script:
    - mkdir -p output
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    # GOARCH is defined explicitly so that it works in arm64 as well
    - CGO_ENABLED=0 GOARCH=amd64 go build -tags netgo -a -v -o output/c4ghtransit c4ghtransit/cmd/c4ghtransit/main.go
  artifacts:
    expose_as: 'c4ghtransit'
    paths:
      - output/c4ghtransit
    expire_in: "60 mins"

# This job requires that you have deleted c4ghtransit-fixed from Artifactory.
# The created binary has such a niche use case that it seemed better to have it
# be manually updated and not have proper release tags
build-fixed-binary:
  stage: build
  tags:
    - sds-build
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: manual
  before_script:
    - mkdir -p output
    - jf config import "${JF_CONFIG_READ_ONLY}"
    - cp dev-tools/mock_entropy.go.txt c4ghtransit/mock_entropy.go
    - go mod tidy
  script:
    - CGO_ENABLED=0 GOARCH=amd64 go build -tags netgo -a -v -o output/c4ghtransit-fixed c4ghtransit/cmd/c4ghtransit/main.go
  after_script:
    - rm -f c4ghtransit/mock_entropy.go
  artifacts:
    expose_as: 'c4ghtransit-fixed'
    paths:
      - output/c4ghtransit-fixed
    expire_in: "60 mins"

build-openapi:
  stage: build
  tags:
    - sds-build
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build-binary
      artifacts: true
  before_script:
    - mkdir -p vault/plugins
    - mv output/c4ghtransit vault/plugins
    - bash dev-tools/vault.sh &
  script:
    - sleep 5
    - bash dev-tools/generate_openapi.sh
  artifacts:
    expose_as: 'c4ghtransit-openapi-schema'
    paths:
      - dev-tools/openapi.json
    expire_in: never

scan-binary:
  stage: scan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME != "renovate-bot"'
      variables:
        WATCH: sds-watch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME == "renovate-bot"'
      variables:
        WATCH: sds-renovate
  tags:
    - sds-test
  before_script:
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - jf scan --licenses --extended-table --watches=$WATCH output/c4ghtransit

push-binary:
  stage: push
  tags:
    - sds-upload
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    JFROG_CLI_BUILD_PROJECT: sds
  before_script:
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG}"
  script:
    - echo Pushing "${CI_COMMIT_TAG}" plugin build
    - >
      jf rt u output/c4ghtransit --build-name=$CI_PROJECT_NAME --build-number=$CI_COMMIT_TAG
      $ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/c4ghtransit-${CI_COMMIT_TAG}
    - jf rt build-publish "$CI_PROJECT_NAME" "$CI_COMMIT_TAG"

push-fixed-binary:
  stage: push
  tags:
    - sds-upload
  needs:
    - build-fixed-binary
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  before_script:
    - jf config import "${JF_CONFIG}"
  script:
    - echo Pushing latest plugin build with fixed public keys
    - jf rt u output/c4ghtransit-fixed "$ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/c4ghtransit-fixed"

release:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)
    assets:
      links:
        - name: c4ghtransit-${RELEASE_VERSION} (artifactory)
          url: ${ARTIFACTORY_URL}/artifactory/${ARTIFACTORY_BINARY_REPO}/${CI_PROJECT_NAME}/c4ghtransit-${RELEASE_VERSION}
