stages:
  - lint
  - test
  - build
  - release

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOCACHE: $CI_PROJECT_DIR/.go-build

lint:
  stage: lint
  extends: .go-cache
  variables:
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache
  rules:
    # We don't run on tags and default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
      when: never
  tags:
    - sds
  script:
    - mkdir -p .cache
    - golangci-lint run -v ./... --timeout 10m -E bodyclose,gocritic,gofmt,gosec,govet,nestif,nlreturn,revive,rowserrcheck --exclude G401,G501,G107 --out-format code-climate | tee gl-code-quality-report.json
    - go fmt ./...
    - go vet ./...
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  after_script:
    - sudo rm -rf .go/pkg

jfrog-go-audit:
  stage: test
  rules:
    # We don't run on tags and default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
      when: never
  tags:
    - sds
  script:
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG}"
    - jf go-config --repo-resolve $ARTIFACTORY_SERVER
    # Audit Go project
    - jf audit --go --licenses --extended-table --min-severity=Medium

test:
  stage: test
  rules:
    # We don't run on tags and default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
      when: never
  tags:
    - sds
  script:
    - GO_BIN=$(which go)
    - sudo ${GO_BIN} test -timeout 30m -v ./c4ghtransit

build-binary:
  stage: build
  tags:
    - sds
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
  script:
    - mkdir -p output
    - CGO_ENABLED=0 go build -tags netgo -a -v -o output/c4ghtransit c4ghtransit/cmd/c4ghtransit/main.go
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG}"
    # Scan binary
    - jf s --licenses output/c4ghtransit --repo ${ARTIFACTORY_SERVER_BINARY_REPO}
    - >
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        echo Pushing latest plugin build
        jf rt u output/c4ghtransit "$ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/c4ghtransit"
      else
        echo Pushing "${CI_COMMIT_TAG}" plugin build
        jf rt u output/c4ghtransit $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/c4ghtransit-${CI_COMMIT_TAG}
      fi
  after_script:
    - echo "BINARY_JOB_ID=$CI_JOB_ID" >> binary_job_id.env
  artifacts:
    expose_as: 'c4ghtransit'
    paths:
      - output/c4ghtransit
    expire_in: never
    reports:
      dotenv: binary_job_id.env


build-openapi:
  stage: build
  image:
    name: docker.io/hashicorp/vault:1.16
    entrypoint: [""]
  tags:
    - docker-exec
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
  needs:
    - job: build-binary
      artifacts: true
  before_script:
    - apk add bash jq git wget curl
    - mkdir -p vault/plugins
    - mv output/c4ghtransit vault/plugins
    - bash dev-tools/vault.sh &
  script:
    - sleep 5
    - bash dev-tools/generate_openapi.sh
  after_script:
    - echo "OPENAPI_JOB_ID=$CI_JOB_ID" >> openapi_job_id.env
  artifacts:
    expose_as: 'c4ghtransit-openapi-schema'
    paths:
      - dev-tools/openapi.json
    expire_in: never
    reports:
      dotenv: openapi_job_id.env


release:
  extends: .automated-release
  needs:
    - job: prepare-release
      artifacts: true
    - job: generate-changelog
      artifacts: true
      optional: true
    - job: build-binary
      artifacts: true
    - job: build-openapi
      artifacts: true
  release:
    description: $(cat release_changes.md)
    assets:
      links:
        - name: c4ghtransit-${RELEASE_VERSION} (artifactory)
          url: https://$ARTIFACTORY_SERVER/artifactory/$ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/c4ghtransit-${RELEASE_VERSION}
        - name: c4ghtransit-${RELEASE_VERSION} (gitlab)
          url: $CI_PROJECT_URL/-/jobs/$BINARY_JOB_ID/artifacts/raw/dev-tools/openapi.json
        - name: c4ghtransit-${RELEASE_VERSION}-openapi-schema.json
          url: $CI_PROJECT_URL/-/jobs/$OPENAPI_JOB_ID/artifacts/raw/output/c4ghtransit
