stages:
  - test
  - build-push

test:
  stage: test
  tags:
    - sds
  script:
    - GO_BIN=$(which go)
    - sudo ${GO_BIN} test -v ./c4ghtransit

build-push:
  stage: build-push
  tags:
    - sds
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
  script:
    - go build -v -o c4ghtransit c4ghtransit/cmd/c4ghtransit/main.go
     if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        echo Pushing latest plugin build
        curl -u $ARTIFACTORY_USER:$ARTIFACTORY_USER_PASSWORD -X PUT "https://$ARTIFACTORY_SERVER/artifactory/sds-generic-local/$CI_PROJECT_NAME/c4ghtransit" -T c4ghtransit
      else
        echo Pushing "${CI_COMMIT_TAG}" plugin build
        curl -u $ARTIFACTORY_USER:$ARTIFACTORY_USER_PASSWORD -X PUT "https://$ARTIFACTORY_SERVER/artifactory/sds-generic-local/$CI_PROJECT_NAME/c4ghtransit-${CI_COMMIT_TAG}" -T "c4ghtransit-${CI_COMMIT_TAG}"
      fi
